name: Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: Verify Yarn version
        run: yarn --version

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        run: |
          cd frontend
          yarn install --immutable

      - name: Log Environment Variables with Checks
        run: |
          echo "---- Environment Variables Debug ----"

          # Print length of the client ID (GUIDs are typically 36 characters)
          echo "NEXT_PUBLIC_MSAL_CLIENT_ID length: ${#NEXT_PUBLIC_MSAL_CLIENT_ID}"
          if [ ${#NEXT_PUBLIC_MSAL_CLIENT_ID} -eq 36 ]; then
            echo "Client ID length appears valid."
          else
            echo "Warning: Unexpected Client ID length: ${#NEXT_PUBLIC_MSAL_CLIENT_ID}"
          fi

          # Print length of the authority token
          echo "NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN length: ${#NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN}"

          # Check the redirect URI – it should be a valid absolute URI (typically starting with "https://")
          echo "NEXT_PUBLIC_MSAL_REDIRECT_URI: $NEXT_PUBLIC_MSAL_REDIRECT_URI"
          if [[ "$NEXT_PUBLIC_MSAL_REDIRECT_URI" == https://* ]]; then
            echo "Redirect URI appears valid (starts with https://)."
          else
            echo "Warning: Redirect URI may be invalid: $NEXT_PUBLIC_MSAL_REDIRECT_URI"
          fi

          echo "--------------------------------"
        env:
          NEXT_PUBLIC_MSAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_MSAL_CLIENT_ID }}
          NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN: ${{ secrets.NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN }}
          NEXT_PUBLIC_MSAL_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_MSAL_REDIRECT_URI }}

      - name: Build Next.js app
        run: |
          cd frontend
          export NODE_OPTIONS="--max-old-space-size=4096"
          yarn build
        env:
          NEXT_PUBLIC_MSAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_MSAL_CLIENT_ID }}
          NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN: ${{ secrets.NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}

      - name: Prepare deployment package
        run: |
          rm -rf deploy-package
          mkdir deploy-package
          # Copy the entire .next folder so that all build files (manifests, etc.) are included.
          cp -R frontend/.next deploy-package/.next
          # Copy the public assets.
          cp -R frontend/public deploy-package/public
          # Copy package.json (and any other needed files) for runtime if required.
          cp frontend/package.json deploy-package/package.json

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: deploy-package
