name: Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Enable Corepack and install correct Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate

      - name: Install dependencies
        run: |
          cd frontend
          yarn install --immutable

      - name: Build Next.js app
        run: |
          cd frontend
          export NODE_OPTIONS="--max-old-space-size=4096"
          yarn build

          if [ ! -d ".next" ]; then
            echo "Error: Build failed - .next directory not created"
            exit 1
          fi
        env:
          NEXT_PUBLIC_MSAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_MSAL_CLIENT_ID }}
          NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN: ${{ secrets.NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN }}
          NEXT_PUBLIC_MSAL_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_MSAL_REDIRECT_URI }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}

      - name: Prepare deployment package
        run: |
          rm -rf deploy-package
          mkdir deploy-package
          cp -R frontend/.next/standalone/* deploy-package/
          mkdir -p deploy-package/.next
          cp -R frontend/.next/static deploy-package/.next/static
          cp -R frontend/public deploy-package/public

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: deploy-package
