name: Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Enable Corepack and install correct Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate

      - name: Install dependencies
        run: |
          cd frontend
          yarn install --immutable

      - name: Debug Installed Dependencies
        run: |
          cd frontend
          yarn why next || echo "Next.js is NOT installed!"

      - name: Force Install Next.js (if missing)
        run: |
          cd frontend
          yarn add next --exact
        if: failure()

      - name: Build Next.js app
        run: |
          cd frontend
          yarn build
        env:
          NEXT_PUBLIC_MSAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_MSAL_CLIENT_ID }}
          NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN: ${{ secrets.NEXT_PUBLIC_MSAL_AUTHORITY_TOKEN }}
          NEXT_PUBLIC_MSAL_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_MSAL_REDIRECT_URI }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}

      - name: Prepare deployment package
        run: |
          # Remove any previous package folder and create a new one
          rm -rf deploy-package
          mkdir deploy-package
          # Copy everything from the standalone build output
          cp -R frontend/.next/standalone/* deploy-package/
          # Copy the static assets folder from the build output
          mkdir -p deploy-package/_next
          cp -R frontend/.next/static deploy-package/_next/static
          # List final folder structure for debugging purposes
          ls -R deploy-package

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: deploy-package
